---
- name: Copy datatypes and tool conf files
  copy:
    src: "{{ tmp_dir }}/config/{{ item }}"
    dest: "{{ galaxy_config_dir }}/{{ item }}"
    remote_src: yes
  loop:
    - datatypes_conf.xml
    - tool_conf.xml
- name: Copy the tools directory
  copy:
    src: "{{ tmp_dir }}/tools"
    dest: "{{ galaxy_server_dir }}/tools"
    owner: "{{ galaxy_user.name }}"
- name: Copy datatype converters to galaxy/lib
  unarchive:
    src: "{{ tmp_dir }}/lib"
    dest: "{{ galaxy_server_dir }}/lib"
    owner: "{{ galaxy_user.name }}"
- name: Copy the index.html
  copy:
    src: "{{ tmp_dir}}/index.html"
    dest: "{{ galaxy_server_dir }}/static/{{ index_html }}"
- name: Copy files and directories
  copy:
    src: "{{ tmp_dir }}/{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ galaxy_user.name }}"
    remote_src: yes
    loop:
      - src: index.html
        dest: "{{ galaxy_server_dir }}/static"
      - src: base.scss
        dest: "{{ galaxy_server_dir }}/client/galaxy/style/scss"
      - src: lib
        dest: "{{ galaxy_server_dir }}/lib"
      - src: tools
        dest: "{{ galaxy_server_dir }}/tools"
      - src: config/datatypes_conf.xml
        dest: "{{ galaxy_config_dir }}"
      - src: config/tool_conf.xml
        dest: "{{ galaxy_config_dir }}"
